sudo: required
services:
  - docker

language: php

cache:
    - vendor
php:
    - '7.1'

before_script:
  - composer install -o

after_script:
    - |
      if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
        travis_retry wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
      fi

after_success: ./etc/docker/deploy.sh

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version

script: phpunit --configuration phpunit.xml