version: '2'
services:
    database:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: webhooks
            POSTGRES_DB: webhooks
            POSTGRES_USER: webhooks
        ports:
            - "5434:5432"

    rabbit:
        image: dzubchik/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"

    app:
        build:
            dockerfile: etc/docker/php/Dockerfile
            context: .
        ports:
           - "8082:8080"
        volumes:
            - .:/app
        links:
            - rabbit
            - database
        working_dir: /app