webhooks:
    path: /webhooks
    defaults:
        _controller: WebhookBundle:Webhook:create
    methods:
        - POST
webhooks_get:
    path: /webhooks/{id}
    defaults:
        _controller: WebhookBundle:Webhook:get
    methods:
        - GET

webhooks_get_reference:
    path: /webhooks/reference/{id}
    defaults:
        _controller: WebhookBundle:Webhook:getByReference
    methods:
        - GET

webhooks_get_last:
    path: /webhooks/
    defaults:
        _controller: WebhookBundle:Webhook:getLast
    methods:
        - GET
